<<NOTE.!
  Problem 2 Even Fibonacci numbers

  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
NOTE

class Fibonacci
  class << self
    @@array = [1, 1]
  end

  def where(&condition)
    while yield base.last
      tic
    end
    base.select(&condition)
  end

  def info
    base.dup
  end

  private
  def base
    @@array
  end

  def tic
    base << base[-2..-1].inject(:+)
  end
end


fi = Fibonacci.new

x = fi.where{|n| n < 4_000_000 }
      .select{|n| n % 2 == 0}
      .inject(:+)

puts "A. #{x}"
p fi.info
